from youtube_transcript_api import YouTubeTranscriptApi
import json, re

VIDEO_ID = "3Xb8C01WpXc"

ytt = YouTubeTranscriptApi()
transcript = list(ytt.fetch(VIDEO_ID, languages=["it"]))

segments = []
for item in transcript:
    start = item.start
    text = item.text
    mins = int(start // 60)
    secs = int(start % 60)
    segments.append({
        "timestamp": f"{mins:02d}:{secs:02d}",
        "start": start,
        "text": text
    })

full_text = " ".join([s["text"] for s in segments])

# Trova inizio sezione voti
match_start = re.search(r"adesso dobbiamo vedere i voti", full_text, re.IGNORECASE)
if not match_start:
    match_start = re.search(r"tempo di nominare le concorrente.*?voti", full_text, re.IGNORECASE)

if not match_start:
    print("Sezione voti non trovata.")
    exit(1)

voti_text = full_text[match_start.start():match_start.start()+3500]

print("=== TESTO SEZIONE VOTI ===")
print(voti_text)
print("\n" + "="*60 + "\n")

# Dividiamo in frasi approssimative per analisi
# Cerchiamo pattern tipo: <keyword> ... <numero> 
# dove i numeri possono essere: 6, 7, 8, 9, 10, 6.5, 7.5, 8.5, 7+, 8-, "set", "meno"

ratings = {}
evidence = []

def normalize_vote(v):
    v = v.strip().lower()
    if v in ["pieno", "pienissima", "pienissimo"]:
        return 10
    if v == "set":
        return 7
    # rimuovi spazi tra numero e decimale
    v = re.sub(r"(\d)\s+e\s+(mezzo|mez|me)", r"\1.5", v)
    v = re.sub(r"(\d)\s*-\s*", r"\1", v)  # gestire "8 -"
    # "8 meno" -> 7.5
    v = re.sub(r"(\d)\s+meno", r"\1.5", v)
    # "8 e troppo" -> ignora, cerca altro
    # Rimuovi spazi
    v = v.replace(" ", "")
    plus = "+" if "+" in v else ""
    v_clean = v.replace("+", "")
    try:
        n = float(v_clean)
        if n == int(n):
            return str(int(n)) + plus
        return str(n) + plus
    except:
        return v + plus

def find_evidence(field, keyword, pattern):
    # Cerca nel testo completo della sezione voti
    m = re.search(pattern, voti_text, re.IGNORECASE | re.DOTALL)
    if m:
        val = normalize_vote(m.group(1))
        ratings[field] = val
        # Trova segmento corrispondente
        phrase = m.group(0)
        for seg in segments:
            if m.group(1) in seg["text"] or keyword.lower() in seg["text"].lower():
                evidence.append({
                    "field": field,
                    "timestamp": seg["timestamp"],
                    "text": seg["text"]
                })
                break

# Regex mirate
find_evidence("punto_dolce", "punto dolce", r"punto dolce.*?Le darei un ([^\.\n]{2,25})")
find_evidence("uscita_di_palla", "Uscita di palla", r"Uscita di palla.*?Le voglio dare un ([^\.\n]{2,25})")
find_evidence("potenza", "Potenza", r"Potenza.*?mi fermo ad un ([^\.\n]{2,25})")
find_evidence("controllo", "Controllo", r"Controllo.*?fermarsi al ([^\.\n]{2,25})")
find_evidence("spin", "spin", r"Spin.*?un ([^\.\n]{2,25}) tranquillamente")
find_evidence("feeling", "Feeling", r"Feeling.*?ma un ([^\.\n]{2,25}) glielo voglio dare")
find_evidence("maneggevolezza", "maneggevolezza", r"maneggevolezza.*?mi fermo al ([^\.\n]{2,25})")
find_evidence("gioco_dal_fondo", "gioco dal fondo", r"gioco dal fondo.*?([^\.\n]{2,25}) glielo voglio dare")
find_evidence("gioco_al_volo", "gioco di volo", r"gioco di volo.*?direi ([^\.\n]{2,25}), le voglio dare")

result = {
    "source": "youtube_transcript",
    "videoId": VIDEO_ID,
    "videoTitle": "Babolat AIR VERON 2026 - Meglio, decisamente meglio!",
    "author": "Fabio Ferro",
    "language": "it",
    "isAutoGenerated": True,
    "ratings": ratings,
    "evidence": evidence,
    "confidence": 0.70,
    "note": "Gergo del recensore: 'set'=7, '8 meno'=7.5. La transcript ASR presenta errori di battitura."
}

print(json.dumps(result, indent=2, ensure_ascii=False))
