import json, re, sys, os
from datetime import datetime, timedelta
from youtube_transcript_api import YouTubeTranscriptApi
from yt_dlp import YoutubeDL

VIDEO_IDS = [
    "m0Sm5uZPiH0", "b-33JiBBqlM", "vuDZ08hCt28", "3Xb8C01WpXc",
    "ACrQD5_ZhiI", "JwgC9D4TIGo", "bnjB18ysBhY", "Ppma9jMypD4",
    "Ug8M2nZ4ei4", "J03ZwFBHfCc",
]

CATEGORIES_ORDERED = [
    ("sweet_spot",      ["sweet spot", "punto dolce"]),
    ("uscita_di_palla", ["uscita di palla", "uscita palla"]),
    ("potenza",         ["potenza"]),
    ("feeling",         ["feeling", "tattile", "tatt"]),
    ("controllo",       ["controllo"]),
    ("spin",            ["spin"]),
    ("maneggevolezza",  ["maneggevolezza", "maneggevole"]),
    ("gioco_dal_fondo", ["gioco dal fondo", "dal fondo", "dal fondo e"]),
    ("gioco_al_volo",   ["gioco al volo", "al volo", "vole"]),
]

# The reviewer says these before each category in the voti section
VOTI_TRIGGERS = [
    r'iniziamo\s+con\s+i\s+voti',
    r'verso\s+i\s+voti',
    r'adesso\s+i\s+voti',
    r'vediamo\s+i\s+voti',
    r'passiamo\s+ai\s+voti',
    r'e\s+i\s+voti',
    r'voti\.?\s+sweet',
    r'partiamo\s+con\s+il\s+voto',
]

ytt = YouTubeTranscriptApi()


def get_video_title(video_id):
    try:
        with YoutubeDL({"quiet": True, "no_warnings": True}) as ydl:
            info = ydl.extract_info(f"https://www.youtube.com/watch?v={video_id}", download=False)
            return info.get("title", "")
    except Exception:
        return ""


def sec_to_hms(s):
    m = int(s // 60)
    sec = int(s % 60)
    return f"{m}:{sec:02d}"


def parse_voto(text):
    text = text.lower().strip()

    if re.search(r'pienissima', text):
        return 10, 'word'
    if re.search(r'(?<!\w)pieno(?!\w)', text):
        return 10, 'word'
    if re.search(r'pien', text):
        return 10, 'word'

    m = re.search(r'(\d+)\s*[+]|(\d+)\s*pi[u\xf9]', text)
    if m:
        n = m.group(1) or m.group(2)
        return f"{n}+", 'numeric'

    m = re.search(r'(\d+)\s*meno|(\d+)\s*[-]', text)
    if m:
        n = m.group(1) or m.group(2)
        return f"{n}-", 'numeric'

    m = re.search(r'(\d+)\s*e\s*me(?:zz[ao])?', text)
    if m:
        return float(m.group(1)) + 0.5, 'numeric'

    m = re.search(r'(?:un|una|del|le\s+do\s+un|posso\s+dare\s+un|mi\s+fermo\s+al)\s+(\d{1,2}(?:\.\d)?)', text)
    if m:
        v = float(m.group(1))
        if 1 <= v <= 10:
            return v, 'numeric'

    m = re.search(r'\b(\d{1,2}(?:\.\d)?)\b', text)
    if m:
        v = float(m.group(1))
        if 1 <= v <= 10:
            return v, 'numeric'

    return None, None


def extract_nearby_number(texts_around, max_look=5):
    combined = ' '.join(texts_around[:max_look]).lower()
    val, vtype = parse_voto(combined)
    if val is not None:
        return val, vtype
    for i in range(1, len(texts_around)):
        combined = ' '.join(texts_around[:i+1]).lower()
        val, vtype = parse_voto(combined)
        if val is not None:
            return val, vtype
    return None, None


def find_voti_start(transcript):
    for i, item in enumerate(transcript):
        txt = item.text.lower()
        for pat in VOTI_TRIGGERS:
            if re.search(pat, txt):
                return i
    for i, item in enumerate(transcript):
        txt = item.text.lower()
        if 'voti' in txt and item.start > 300:
            return i
    return len(transcript) // 2


def extract_ratings_for_video(video_id):
    result = {
        "videoId": video_id,
        "url": f"https://www.youtube.com/watch?v={video_id}",
        "title": "",
        "channel": "Fabio Ferro",
        "language": "it",
        "isAutoGenerated": True,
        "ratings": {cat: None for cat, _ in CATEGORIES_ORDERED},
        "evidence": [],
        "confidence": 0,
        "confidence_details": {
            "categories_found": 0,
            "categories_expected": 9,
            "ratings_with_numeric_value": 0,
            "ratings_with_word_value": 0,
            "ratings_with_truncated_asr": 0,
        },
        "extraction_date": datetime.now().strftime("%Y-%m-%d"),
    }

    try:
        result["title"] = get_video_title(video_id)
    except Exception:
        pass

    try:
        transcript = ytt.fetch(video_id, languages=["it"])
        result["language"] = "it"
    except Exception:
        try:
            transcript = ytt.fetch(video_id)
            result["language"] = getattr(transcript, 'language', 'unknown')
        except Exception as e:
            result["error"] = "transcript_not_available"
            result["confidence"] = 0
            return result

    tl = list(transcript)
    if not tl:
        result["error"] = "transcript_empty"
        result["confidence"] = 0
        return result

    start_i = find_voti_start(tl)
    window = tl[start_i: min(len(tl), start_i + 350)]

    # extract target_player from full window
    full_text = ' '.join(item.text.lower() for item in window)
    mp = re.search(r'(?:per|adatto a|consigliata per|ideale per)\s+(?:un\s+)?(giocatore\s+)?(intermedio\s*(?:e\s*)?(?:intermedio\s*)?(?:avanzato|principiante|professionista)?)', full_text)
    if mp:
        result["target_player"] = mp.group(0).replace('per ', '').replace('adatto a ', '').replace('consigliata per ', '').replace('ideale per ', '').strip()

    # competitor mentions - simpler
    comp_names = set()
    for m in re.finditer(r'(?:concorrenti?|confronto con|rispetto a(?:lla|l)?)\s+[:\s]*([^.,;]+)', full_text):
        name = m.group(1).strip()
        if 3 < len(name) < 80:
            comp_names.add(name.title())
    if comp_names:
        result["competitors_mentioned"] = [{"name": n} for n in comp_names]

    # Now scan forward in the window looking for categories + numbers
    used_indices = set()
    for cat_key, cat_keywords in CATEGORIES_ORDERED:
        best = None
        for i in range(len(window)):
            if i in used_indices:
                continue
            txt = window[i].text.lower()
            if any(kw in txt for kw in cat_keywords):
                # look for a number nearby
                look_fwd = [window[j].text for j in range(i, min(len(window), i + 4))]
                val, vtype = extract_nearby_number(look_fwd)
                note = ""
                if val is not None:
                    if vtype == 'word':
                        note = f"voto espresso in parole"
                        result["confidence_details"]["ratings_with_word_value"] += 1
                    else:
                        result["confidence_details"]["ratings_with_numeric_value"] += 1
                    result["ratings"][cat_key] = val
                    result["confidence_details"]["categories_found"] += 1
                    best = {
                        "category": cat_key,
                        "timestamp_seconds": window[i].start,
                        "timestamp_hhmmss": sec_to_hms(window[i].start),
                        "original_text": window[i].text,
                        "note": note,
                    }
                    used_indices.add(i)
                    break
                else:
                    # check nothing more useful
                    pass
        if best:
            result["evidence"].append(best)

    # confidence
    cf = result["confidence_details"]
    conf = 0.1 if result["language"] == "it" else 0.05

    cat_ratio = cf["categories_found"] / cf["categories_expected"]
    conf += 0.3 * cat_ratio
    conf += 0.1 * cf["ratings_with_numeric_value"]
    conf += 0.05 * cf["ratings_with_word_value"]
    if cf["categories_found"] < 5:
        conf -= 0.1

    for v in result["ratings"].values():
        if isinstance(v, (int, float)):
            if v < 1 or v > 10:
                conf -= 0.1

    result["confidence"] = round(min(max(conf, 0), 1), 2)
    if result["confidence"] < 0.5:
        result["needs_review"] = True

    return result


def main():
    all_results = []
    output_dir = "data/ratings"
    os.makedirs(output_dir, exist_ok=True)

    for vid in VIDEO_IDS:
        print(f"Processing: {vid}...", file=sys.stderr)
        try:
            res = extract_ratings_for_video(vid)
            all_results.append(res)
            fname = os.path.join(output_dir, f"{vid}.json")
            with open(fname, "w", encoding="utf-8") as f:
                json.dump(res, f, ensure_ascii=False, indent=2)
            print(f"  -> Saved {fname}", file=sys.stderr)
        except Exception as e:
            err = {
                "videoId": vid,
                "url": f"https://www.youtube.com/watch?v={vid}",
                "error": str(e),
                "confidence": 0,
            }
            all_results.append(err)
            print(f"  -> ERROR: {e}", file=sys.stderr)

    combined_path = os.path.join(output_dir, "_all.json")
    with open(combined_path, "w", encoding="utf-8") as f:
        json.dump(all_results, f, ensure_ascii=False, indent=2)
    print(f"\nCombined results saved to {combined_path}", file=sys.stderr)

    # print summary
    for r in all_results:
        found = sum(1 for v in r.get("ratings", {}).values() if v is not None)
        err = r.get("error", "")
        c = r.get("confidence", 0)
        tid = r["videoId"]
        if err:
            print(f"  {tid}: ERROR - {err}")
        else:
            print(f"  {tid}: {found}/9 ratings found, confidence={c:.2f}")


if __name__ == "__main__":
    main()
